# MyBatis-Plus Config
mybatis-plus:
  type-aliases-package: online.lianxue.cms.*.entity


server:
  port: 8080

spring:
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

