log_home: D:\\logs
spring:
  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://106.15.43.169:3307/aixue?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: yunbandan.1

  redis:
    host: master.nitrogen-dpc-redis-sit.zjzejd.use1.cache.amazonaws.com
    port: 6379
    password: sZwPVkgpn53jc9yg
    timeout: 10000ms

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl